### ISSUE TITLE
"Won't parse" in HyperDoc when clicking on finiteAggregate in the Aggregate Category page

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#203]
In HyperDoc if you browse for Aggregate category and on the displayed page you click on finiteAggregate I obtain this:

<img width="708" height="474" alt="Image" src="https://github.com/user-attachments/assets/707bb669-b96f-45d3-9f1b-2530755fda85" />

And in the interpreter:

<code>
   >> System error:
   Argument:

    to spadType won't parse
</code>

**Comment by hemmecke** [comment]
Sorry. I run Fricas 1.3.12 (3f7be90e46381aec9a5c5a5363052a5496d91ba6) and see a window titled "Unexposed Category finiteAggregate" after the click. Using grep, I even do not find \spadType in any of the .spad files. So my conclusion is that you use an older version of FriCAS.

Maybe you should follow your own advice and provide the version information together with your bugreport. ;-)

**Comment by hemmecke** [comment]
"Version: FriCAS 2025-04-14" ??? somehow I suspect that when you type "fricas" on the commandline you still get your old version. What does "type fricas" return in your case?

And no "spadType" is not a function. It is rather a tag in the documentation written as \spadType{finiteAggregate}. But wait. Why do you see spadType with a capital T?
src/doc/ht/util.ht indead translates \spadtype{finiteAggregate}
https://github.com/fricas/fricas/blob/master/src/algebra/aggcat.spad#L19
to |spadType|. The rest must be a problem with boot code.
But why would it work for me and not for you?

**Comment by gvanuxem** [comment]
Ralf, your version comes from another branch where version is bumped. I use the main branch.

The offending commit is:

66d643e7789c0254f9a88555f559f96867b8c77e
Pass more Hyperdoc requests as strings
5 July, 2025

If I revert this change:
`\newcommand{\spadtype}[1]{\lispdownlink{#1}{(|spadType| '|#1|)}}`
to
\newcommand{\spadtype}[1]{\lispdownlink{#1}{(|spadType| "#1")}}

The cited issue is gone away (use '|#1| instead of the new version)

**Comment by oldk1331** [comment]
Verified fixed by 3dde9cbd2f6cfa149c7cdee765a4fe2fa39fb5b6.
